---
- hosts: nginx
  tasks:
    - name: Installation nginx
      apt:
        name: nginx
      become: yes

- hosts: node1
  tasks:
    - name: Deploiement index node 1
      copy:
        dest: /var/www/html/index.html
        content: 'Coucou du Node 1!'
      become: yes

- hosts: node2
  tasks:
   - name: Deploiement index node 2
     copy:
       dest: /var/www/html/index.html
       content: 'Coucou du Node 2!'
     become: yes

- hosts: lb
  tasks:
   - name: Copie nginx.conf sur le load-balancer
     copy:
       src: nginx.conf
       dest: /etc/nginx/sites-enabled/default
     become: yes
   - name: Restart nginx
     service:
       name: nginx
       state: restarted
     become: yes

